# Auto-generated by capfire's release workflow. Do not edit by
# hand — changes will be overwritten on the next release.
# Source template: packaging/homebrew/capfire.rb in
# https://github.com/ricardo5401/capfire
class Capfire < Formula
  desc "JWT-authenticated deploy orchestrator — developer CLI"
  homepage "https://github.com/ricardo5401/capfire"
  version "0.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/ricardo5401/capfire/releases/download/v0.4.0/capfire-v0.4.0-darwin-amd64.tar.gz"
      sha256 "e234ae1c27f7f9e4d13ddfbe1034db8287093b3fe6865229228c504a5c4865a7"
    end
    on_arm do
      url "https://github.com/ricardo5401/capfire/releases/download/v0.4.0/capfire-v0.4.0-darwin-arm64.tar.gz"
      sha256 "8671ccb0e5498f270400fc00a2ea815657d6a6d74747334d7942205527b18ceb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ricardo5401/capfire/releases/download/v0.4.0/capfire-v0.4.0-linux-amd64.tar.gz"
      sha256 "f03ceea77024ba22a7e02023aac53adcc97e6e522cd082c124553b1972a330d3"
    end
    on_arm do
      url "https://github.com/ricardo5401/capfire/releases/download/v0.4.0/capfire-v0.4.0-linux-arm64.tar.gz"
      sha256 "1f3edd6407e964f1829752abe74d0be594aa92edc065129368a199aacb11a38d"
    end
  end

  def install
    bin.install "capfire"
  end

  test do
    assert_match "capfire version", shell_output("#{bin}/capfire --version")
  end
end
